const axios = require('axios'); const http = require('http'); const fs = require('fs'); const TELEGRAM_BOT_TOKEN = "8718062927:AAG9ix0H9UIt51oXZqRrdaNynBvHU-zzmOI"; const TELEGRAM_CHAT_ID = "-1003816646344"; const WEBSITE_URL = "https://appointment.bmeia.gv.at"; const TARGET_VISA = "Familienzusammenführung gem. NAG"; let sentSlots = JSON.parse(fs.existsSync('sent_slots.json') ? fs.readFileSync('sent_slots.json') : '[]'); let stats = { startTime: new Date(), totalChecks: 0, slotsFound: 0, notificationsSent: 0 }; async function sendTelegram(msg) { try { await axios.post(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, { chat_id: TELEGRAM_CHAT_ID, text: msg, parse_mode: 'HTML', reply_markup: { inline_keyboard: [[{ text: "🔗 احجز الآن!", url: WEBSITE_URL }]] } }); return true; } catch (e) { return false; } } async function fetchWebsite() { try { const res = await axios.get(WEBSITE_URL, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' }, timeout: 20000 }); return res.data; } catch (e) { return null; } } function findSlots(html) { if (!html) return []; const found = []; const dateRegex = /(Mon|Tue|Wed|Thu|Fri|Sat|Sun)[,\s]+(\d{1,2})\/(\d{1,2})\/(\d{4})/gi; let match; while ((match = dateRegex.exec(html)) !== null) { const context = html.substring(Math.max(0, match.index - 100), Math.min(html.length, match.index + 250)); const times = context.match(/\d{1,2}:\d{2}/g) || []; times.forEach(time => { const key = match[1] + "_" + match[2] + "/" + match[3] + "/" + match[4] + "_" + time; if (!sentSlots.includes(key)) { found.push({ day: match[1], date: match[2] + "/" + match[3] + "/" + match[4], time: time, key: key }); } }); } return found; } async function checkSlots() { stats.totalChecks++; const html = await fetchWebsite(); if (!html) return; const slots = findSlots(html); if (slots.length > 0) { stats.slotsFound += slots.length; for (const slot of slots) { const msg = `🚨 موعد جديد! 🚨\n\n🇦🇹 Austria - Cairo\n📄 ${TARGET_VISA}\n\n📅 ${slot.day}, ${slot.date}\n⏰ ${slot.time}\n\n⚡️ احجز الآن قبل فوات الأوان!`; if (await sendTelegram(msg)) { sentSlots.push(slot.key); stats.notificationsSent++; console.log('✅ Slot sent:', slot.day, slot.date, slot.time); } } fs.writeFileSync('sent_slots.json', JSON.stringify(sentSlots)); } else { console.log('🔁 No slots - check #' + stats.totalChecks); } } const PORT = process.env.PORT || 3000; const htmlPage = `
🤖 BMEIA Bot Dashboard

● يعمل الآن 24/7

0
إجمالي التحققات
0
المواعيد
0
الإشعارات
`; http.createServer((req, res) => { if (req.url === '/') { res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' }); res.end(htmlPage); } else if (req.url === '/api') { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ stats })); } else { res.writeHead(404); res.end('Not Found'); } }).listen(PORT, () => { console.log('🤖 BMEIA Bot Started!'); console.log('🌐 Dashboard: http://localhost:' + PORT); setInterval(checkSlots, 30000); checkSlots(); sendTelegram('🤖 البوت started!\n\n✅ يعمل 24/7\n⏰ كل 30 ثانية\n\n🎯 جاهز للمواعيد!'); }); process.on('SIGINT', () => process.exit());